### ISSUE TITLE
Spring 2022 Meeting Items

### ISSUE THREAD

**Issue by mattketk** [UWMRO/Instruments#12]
Meeting notes for Spring 2022

**Comment by mattketk** [comment]
- was able to compile a test implementation of `Initialize`
- need to find a way to include `libandor`

**Comment by mattketk** [comment]
# Breakthrough time!
https://pastebin.com/ejDnqVTT

- make sure the `cpp_name` matches `extension_name`.

**Comment by ojf** [comment]
Two steps, first create a shared object library (libandorbind.so), then compile the python module (andorbind.cpython-310-x86_64-linux-gnu.so)

```
$ g++ -O3 -Wall -Werror -shared -std=c++11 -fPIC $(python3 -m pybind11 --includes) andorbind.cpp -o libandorbind.so

$ g++ -O3 -Wall -Werror -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` -I python3 -I . andorbind.cpp -o andorbind`python3-config --extension-suffix` -L. -landorbind -landor -Wl,-rpath,.
````

**Comment by mattketk** [comment]
# Stuff to add to `andorbind.cpp`
- [x] Initialize(str path)
- [x] SetReadMode(int mode)
- [x] SetAcquisitionMode(int mode)
- [x] SetExposureTime(float time)
- [x] GetDetector(int* xpixels, int* ypixels)
- [x] SetShutter(int typ,int mode, int closingtime, int openingtime)
- [x] StartAcquisition()
- [x] GetStatus(int* status)
- [x] GetAcquiredData(at_32* arr, unsigned long size)
- [ ] SaveAsBmp(char* path, char* palette, long ymin, long ymax) (?)
- [x] ShutDown(void)
- [ ] GetAvailableCameras(long* totalCameras)
- [ ] GetCameraHandle(long cameraIndex, long* cameraHandle)
- [ ] SetCurrentCamera(long cameraHandle)

**Comment by mattketk** [comment]
> Two steps, first create a shared object library (libandorbind.so), then compile the python module (andorbind.cpython-310-x86_64-linux-gnu.so)
> 
> ```
> $ g++ -O3 -Wall -Werror -shared -std=c++11 -fPIC $(python3 -m pybind11 --includes) andorbind.cpp -o libandorbind.so
> 
> $ g++ -O3 -Wall -Werror -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` -I python3 -I . andorbind.cpp -o andorbind`python3-config --extension-suffix` -L. -landorbind -landor -Wl,-rpath,.
> ```

we might consider renaming `andorbind` to `andorwrapper` just to be more descriptive...

**Comment by mattketk** [comment]
# Reading
- making doc strings
- making keyword args in pybind11

**Comment by mattketk** [comment]
![AndorWrapperFirstData](https://user-images.githubusercontent.com/31739174/160260382-ea0703c5-a865-449a-985b-8be21e885147.png)

**Comment by ojf** [comment]
I agree that we might want to rename this. I know I suggested otherwise, but just calling it `andor` would be transparent once we were working in Python

**Comment by mattketk** [comment]
# Meeting Agenda - 04/07/2022
## Overview
- Introductions (Getting started with development)
- Helper Functions 
- Software Design with Exceptions (instead of Andor Error Codes)
- Web App Flask?

## Things to keep in the back of the mind
- with the pybind11 wrapper, functional programming paradigm may be better than object-oriented (reduces complexity)
- implementing exceptions (on top of error codes) may help with troubleshooting in the future

**Comment by mattketk** [comment]
# Meeting Agenda - 05/25/2022
## Overview
- Commentary on [albireox/boson](https://github.com/albireox/boson) (Jose?)
- Sending requests thru buttons
- Receiving image data?
- Databases?
- Considering feedback from Tristan, Matt A. (using Django?)

**Comment by mattketk** [comment]
# 05/25/2022 Minutes
- Considering WebSockets
- https://flask-socketio.readthedocs.io/en/latest/
