### ISSUE TITLE
Converting evora.py return statements to natural types

### ISSUE THREAD

**Issue by ejgl** [UWMRO/Instruments#3]
Right now, most of evora.py's functions return a string that contains the data from andor. We want to convert the format of this data into a dictionary to simplify formatting issues. 
**We don't necessarily want to return dictionaries, but rather put in dictionaries into the functions themselves and return relevant values.**

Things to consider:
- naming conventions of keys
- data is in natural type (float is float, etc.)
- would changing the format have side effects/introduce bugs within other .py files?
- do we want everything to be a dictionary? The things we want especially to become dictionaries are functions that are camera-specific (ex. getTEC)

**Comment by ojf** [comment]
List of methods that interact with the camera in the Evora class

 - [ ] __init__(self):
 - [ ] getStatus(self):
 - [ ] startup(self):
 - [ ] getTEC(self):
 - [ ] setTEC(self, setPoint=None):
 - [ ] warmup(self):
 - [ ] getTemp(self):
 - [ ] getTempRange(self):
 - [ ] shutdown(self):
 - [ ] getTimings(self):
 - [ ] verticalSpeedStats(self, index):
 - [ ] horizontalSpeedStats(self, channel, type, index):
 - [ ] abort(self):
 - [ ] expose(self,
 - [ ] realTimeExposure(self, protocol, imType, itime, binning=1):
 - [ ] kseriesExposure(self,

Ignore these methods, which shouldn't interact with the camera and will move outside of evora.py
- [ ] getHeader(self, attributes):
 - [ ] getHeader_2(self, attributes, tcc):
 - [ ] heimdallChooseLogFile(self, logFileList, obsTime):
 - [ ] heimdallParseLogFile(self, logFile, obsTime):
 - [ ] ChooseLogfile(self, LogfileList, ObsTime):
 - [ ] ParseLogfile(self, LogfileName, ObsTime):
