### ISSUE TITLE
New Andor Driver Software Version

### ISSUE THREAD

**Issue by mattketk** [UWMRO/Instruments#6]
We were able to receive the updated software to control the Andor software (updated just a few months ago too.)

# Installation Instructions

## Installing drivers
1. Ensure that Andor is powered up and that I/O hardware is hooked up to computer
2. Ensure that `libusb-dev` package is installed 
3. Unzip tar.gz file given for Andor software
4. Enter the unzipped folder, issue `sudo bash install_andor`
5. When prompted to read the release notes, answer no.

## Installing examples
1. Locate the `examples/console` folder in the Andor software package
2. Inside `examples/console`, go into one of the folders to run an example (recommended: `generic`, `image`)
3. In any one of the folders, issue `make` command (make sure g++ is installed as well)
4. To run the example code, issue `./generic` if in the generic example, `./image` if in the image example, so on, so forth.

# What's Next

## Writing an interface for the C++ code to be used in Python (the current 'swig' setup only works for the previous version of the Andor driver.)
- peering into examples given in the software download to see how Andor is initialized and controlled in the C++ code
- Points of interest include: `Initialize("/usr/local/etc/Andor")` function, getting/setting cooling, taking an image

## Deciding the new Python-C++ interface
- @ojf will contact some people to see what they might recommend in approaching this project.

**Comment by ojf** [comment]
Conor recommends creating a C++/Python interface with pybind instead of swig--so lets give that a try before trying swig again.
